#!/usr/bin/env python

import os
import sys
import re
import subprocess

AVATAR_STORAGE = os.path.abspath(os.path.join(os.path.dirname(os.path.dirname(__file__)),
                              'avatars'))

def get_avatar(folder, email, width):
    path = os.path.join(folder, email)
    if not os.path.exists(path):
        path = os.path.join(folder, 'default.png')

    command = 'img2txt -W %(width)s %(path)s' % {'path': path,
                                                 'width': width}
    result = subprocess.check_output(command, shell=True)
    return result

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Replaces instances of '
                                     'IMG:foo@bar.org with the associated '
                                     'Gravatar in stdin and prints it to '
                                     'stdout.')
    parser.add_argument('--folder', type=str, default=AVATAR_STORAGE, required=False,
                        help='Folder where to load the pictures from.')
    parser.add_argument('-W', '--width', type=int, default=12, required=False,
                        help='Width of the picture.')
    args = parser.parse_args()

    r = re.compile(r'IMG:([^\s]*)')
    for line in sys.stdin.readlines():
        search = re.search(r, line)
        if search:
            email = search.group(1)
            avatar = get_avatar(args.folder, email, args.width)
            line = re.sub(r, avatar, line)
        try:
            sys.stdout.write(line)
        except Exception:
            sys.exit()
